# FROM python:3
FROM python:3

# Installed dependencies
# RUN

# COPY project fiels to somewhere on the container filesystem
COPY code.py /code/

# CMD python code.py (based on location in containter)
CMD ["python", "/code/code.py"]
